tag_num = 50
ent_num = 19
EMBEDDING_SIZE = 300

BATCH_SIZE = 64
TRAINING_EPOCHS = 2000
LSTM_CELL_HIDDEN_SIZE = 200
HIDDEN_SIZE = 200
FEATURES_SIZE = 73
#USE_DEMO_MODEL_PATH = 'model_trained'
#TEST_MODEL_PATH = 'model_trained'
USE_DEMO_MODEL_PATH = "model_trained_step-1800"
TEST_MODEL_PATH = "model_trained_step-1800"

SAVE_MODEL_PATH = './model_trained_1'
SAVE_STEP_MODEL_PATH = './model_trained_step_1'

EP_FLAG = True
EPOCHS = 5
SAVER_STEP = 200
CHECKER_STEP = 10
ITERATIONS = 2000
Q_MAX_SIZE = 61
C_MAX_SIZE = 768

DOWNLOAD=False
