tag_num = 50
ent_num = 19
EMBEDDING_SIZE = 300
CONTEXT_MAX_SIZE = 767 + 1
QUESTION_MAX_SIZE = 60 + 1
BATCH_SIZE = 64
TRAINING_EPOCHS = 2000
LSTM_CELL_HIDDEN_SIZE = 200
HIDDEN_SIZE = 200
FEATURES_SIZE = 73
USE_DEMO_MODEL_PATH = 'model_trained'
TEST_MODEL_PATH = 'model_trained'

SAVE_MODEL_PATH = './model_trained'
SAVE_STEP_MODEL_PATH = './model_trained_step'

EP_FLAG=False
EPOCHS = 1
SAVER_STEP = 200
CHECKER_STEP = 10
ITERATIONS = 2000
Q_MAX_SIZE = 61
C_MAX_SIZE = 768

DOWNLOAD=False